<a href="https://colab.research.google.com/github/sharique-ansari/ScientificComputing/blob/master/ScmpHW4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



##Sharique Ansari
###2016249
SCMP - Homework 4



In [0]:
from __future__ import division
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import numpy.linalg as npla
import scipy.linalg as spla

##Solution 1

In [0]:
A = np.matrix([[2, 3, 2] , [10, 3, 4] , [3, 6, 1.0]])
x = np.matrix([1.0, 1, 1]).T
iterations = 17

for i in range (iterations):
    # print(f"{i+1}th iteration")
    eigenvalue = npla.norm(x,np.inf)
    x = A*x
    # print(f"norm is {npla.norm(x,np.inf)}")
    x = x/eigenvalue
    
    
print()
print()
print(x)
print()
print()

norm = npla.norm(x)
print (f'{x/norm}')
print (npla.eig(A)[1])



[[ 5.5       ]
 [11.00000001]
 [ 8.25      ]]


[[0.37139068]
 [0.74278135]
 [0.55708601]]
[[ 3.71390676e-01  1.82574186e-01 -4.13692033e-16]
 [ 7.42781353e-01  3.65148372e-01 -5.54700196e-01]
 [ 5.57086015e-01 -9.12870929e-01  8.32050294e-01]]


In [0]:
def invitr(A):
  LUP = spla.lu_factor(A,True)
  n = A.shape[0]
  x = np.matrix([1.0, 1, 1]).T
  spla.lu_solve(LUP,x,True)
  lold = 0
  lmin = 1./npla.norm(x)
  x*=lmin
  for i in range(iterations):
    lold=lmin
    spla.lu_solve(LUP,x,overwrite_b=True)
    lmin = 1./npla.norm(x)
    x*=lmin
  return lmin,-x


In [0]:
invitr(A)

(1.9989544554868255, matrix([[ 0.18276509],
         [ 0.3649273 ],
         [-0.91292113]]))

As can be seen these values are pretty close to minimum eigenvalue and corresponding eigenvector

##Solution 2

In [0]:
A = np.matrix([[6, 2, 1] , [2, 3, 1] , [1, 1, 1.0]])
print (npla.eig(A))
x = np.matrix([1.0, 1, 1]).T
lam = 2
# print(A-np.matrix([[2,0,0],[0,2,0],[0,0,2]]))
inv = npla.inv(A-np.matrix([[2,0,0],[0,2,0],[0,0,2]]))
# print(inv)

iterations = 17

for i in range (iterations):
    # print(f"{i+1}th iteration")
    eigenvalue = npla.norm(x,np.inf)
    
    x = inv*x
    # print(f"norm is {npla.norm(x,np.inf)}")
    x = x/eigenvalue
# print(npla.norm(x))
print()
print()
print("eigenvector closest to 2 is")
print(-x/npla.norm(x))
print("Eigenvalue is")
print((1/eigenvalue)+lam)


(array([7.28799214, 2.13307448, 0.57893339]), matrix([[ 0.86643225,  0.49742503, -0.0431682 ],
        [ 0.45305757, -0.8195891 , -0.35073145],
        [ 0.20984279, -0.28432735,  0.9354806 ]]))


eigenvector closest to 2 is
[[ 0.49742503]
 [-0.8195891 ]
 [-0.28432735]]
Eigenvalue is
2.133074475348525


##Solution 3

In [0]:
from pylab import *
A = array([[6, 2, 1] , [2, 3, 1] , [1, 1, 1.0]])

print ("\nA = ")
print (A)

lam,X = eig(A)

print ("\nEigenvalues: ",lam)

v = randn(3)
print ("\nStarting guess v: ",v)
print (" ")

mu = 1. + 1j
print ("k = %s, mu = %21.16f + %21.16fj" %  (0,mu.real,mu.imag))

for k in range(1,10):
    B = A - mu*eye(3)
    try:
        w = solve(B,v)
    except:
        print ("Matrix is singular!   Converged solution")
        break
    v = w / norm(w,2)
    mu = dot(conj(v.T), dot(A,v))
    print ("k = %s, mu = %21.16f + %21.16fj" %  (k,mu.real,mu.imag))


A = 
[[6. 2. 1.]
 [2. 3. 1.]
 [1. 1. 1.]]

Eigenvalues:  [7.28799214 2.13307448 0.57893339]

Starting guess v:  [ 1.37263286 -1.34031602 -0.04275991]
 
k = 0, mu =    1.0000000000000000 +    1.0000000000000000j
k = 1, mu =    2.0419114581010609 +    0.0000000000000001j
k = 2, mu =    2.1325830696097383 +    0.0000000000000000j
k = 3, mu =    2.1330744752985344 +    0.0000000000000000j
k = 4, mu =    2.1330744753485256 +   -0.0000000000000002j
k = 5, mu =    2.1330744753485251 +    0.0000000000000000j
k = 6, mu =    2.1330744753485251 +    0.0000000000000001j
k = 7, mu =    2.1330744753485256 +   -0.0000000000000001j
k = 8, mu =    2.1330744753485251 +    0.0000000000000000j
k = 9, mu =    2.1330744753485247 +   -0.0000000000000001j


In [0]:
import numpy as np
import math
import pprint
from numpy import linalg as LA

def rayray(A):
	x = np.matrix([1.0, 0, 0]).T

	I = np.matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

	tol = 2*10**(-16)

	ite = 0

	v = []

	u1 = []

	x1 = []

	while True:
		ite = ite + 1
		xT = x.T
		u = (xT*A*x)/(xT*x)
		uk = float(u[0])
		B = A - (uk*I)

		u1.append(uk)

		x = np.linalg.solve(B,x)

		x1.append(x)
		x = x/(np.linalg.norm(x,np.inf))

		if len(x1)>2:
			vnew = np.linalg.norm(x1[-1],np.inf)
			v.append(vnew)
			# print("vnew:")
			# print(vnew)
			vold = np.linalg.norm(x1[-2],np.inf)
			# print("vold:")
			# print(vold)
			if abs((vnew - vold)/vnew) < tol:
				# print((vnew - vold)/vnew)
				break

	print("Rayleigh quotient iteration:-")
	print (f"{ite} iterations")

	print("closest x: ")
	pprint.pprint(x)
	print("eigenvalue: ")
	pprint.pprint(u1[-1])

A1 = np.matrix([[6, 2, 1], [2, 3, 1], [1, 1, 1]])

rayray(A1)

##Solution 4